#!/usr/bin/env bash

if
  [[ -s "/home/vagrant/.rvm/gems/ruby-2.2.1/environment" ]]
then
  source "/home/vagrant/.rvm/gems/ruby-2.2.1/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/vagrant/.rvm/gems/ruby-2.2.1/environment'" >&2
  exit 1
fi
